name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd ${{ github.workspace }}/frontend
          npm install
          npm run build
      
      - name: Build Backend
      - run: |
          cd ${{ github.workspace }}/backend
          npm install
          npm run build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          
#      - name: Deploy backend to render
 #     - uses: actions/checkout@v3
  #    - uses: JorgeLNJunior/render-deploy@v1.3.2
   #     with:
    #      service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
     #     api_key: ${{ secrets.RENDER_API_KEY }} # required
      #    clear_cache: false # Clear build cache. Optional
       #   wait_deploy: false # Wait until the deploy status is successful. Warning! Free Render services can take +5 minutes to be fully deployed. Optional